#
# Makefile for Phoenix-RTOS littlefs port
#
# Copyright 2024 Phoenix Systems
#

NAME := liblfs
LOCAL_HEADERS_DIR := include

# Optional flag for tracing
# LOCAL_CFLAGS += -DLFS_YES_TRACE

LOCAL_SRCS := lfs.c lfs_bd.c lfs_util.c ph_lfs_api.c liblfs.c

include $(static-lib.mk)
