#
# Makefile for Phoenix-RTOS ext2
#
# Copyright 2017, 2018 Phoenix Systems
#

PROGS_SRCS = ext2.c mbr.c inode.c block.c file.c pc-ata.c dir.c object.c sb.c
PROGS = ext2

# include after all dependencies are set
include $(TOPDIR)/Makefile.rules
