#
# Makefile for Phoenix-RTOS meterfs filesystem
#
# Copyright 2018 Phoenix Systems
#

NAME := meterfs
LOCAL_PATH := $(call my-dir)
SRCS := $(wildcard $(LOCAL_PATH)*.c)
LOCAL_HEADERS := meterfs-srv.h

include $(binary.mk)
