#
# Misc. FAT
# Copyright 2012 Pawel Pisarczyk
#

NAME := fat
LOCAL_PATH := $(call my-dir)
SRCS := $(wildcard $(LOCAL_PATH)*.c)
LOCAL_CFLAGS := -D_FILE_OFFSET_BITS=64
LOCAL_HEADERS := fat.h

include $(binary.mk)
