#
# Makefile for Phoenix-RTOS meterfs filesystem
#
# Copyright 2023 Phoenix Systems
#

ifneq ($(TARGET), host-generic-pc)

NAME := libmeterfs-storage
LOCAL_SRCS := meterfs_storage.c
LOCAL_HEADERS := meterfs_storage.h
DEPS := libmeterfs

include $(static-lib.mk)

endif
