#
# Makefile for Phoenix-RTOS 3 filesystems
#
# iMX RT drivers
#
# Copyright 2020 Phoenix Systems
#

CFLAGS += -DTARGET_IMXRT -DTARGET_IMXRT11

include dummyfs/Makefile
#include meterfs/Makefile
#include meterfs/test/Makefile
