#
# Makefile for Phoenix-RTOS 3 filesystems
#
# iMX RT drivers
#
# Copyright 2020 Phoenix Systems
#

CFLAGS += -DTARGET_IMXRT -DTARGET_IMXRT1050

include dummyfs/Makefile
include libmeterfs/Makefile
include ptable/Makefile
