#
# Makefile for Phoenix-RTOS 3 filesystems
#
# STM32L1 drivers
#
# Copyright 2020 Phoenix Systems
#

# FIXME: on STM32L1 TARGET, __TARGET and __CPU are not supported
CFLAGS += -DTARGET_STM32 -DTARGET_STM32L1

DEFAULT_COMPONENTS := meterfs
