#
# Makefile for Phoenix-RTOS FAT filesystem
#
# Copyright 2023 Phoenix Systems
#

NAME := libfat
LOCAL_PATH := $(call my-dir)
SRCS := $(wildcard $(LOCAL_PATH)*.c)
LOCAL_HEADERS := libfat.h

include $(static-lib.mk)
